/* =========================================================
   QUIZ ARENA SERVICE WORKER  (the ONLY service worker)

   Why there is one and not two: a scope ("/") can only have one
   active service worker. The old setup registered sw.js from
   main.js and firebase-messaging-sw.js from pushNotifications.js,
   both at "/", so whichever registered last silently evicted the
   other. Caching and push now live together here;
   firebase-messaging-sw.js is a one-line shim that imports this file.

   What it does
   1. PRECACHE   -- on install, downloads the app shell (index.html,
                    every css/js file, icons) plus the Firebase SDK
                    modules the app imports from gstatic.com, so the
                    app boots with no network at all. Progress is
                    broadcast to the page (welcome screen status line).
   2. RUNTIME    -- navigations: network first, but if the network takes
                    more than 3.5s (bad "lie-fi" data) the cached shell
                    is served instead. Same-origin assets: stale-while-
                    revalidate. Firebase SDK: cache first.
   3. PUSH       -- FCM background notifications (moved from
                    firebase-messaging-sw.js, same behaviour).

   Everything else (Firestore, Auth, Cloud Functions, Flutterwave,
   Cloudinary) is deliberately NOT touched -- those go straight to the
   network. Firestore has its own offline cache (js/firebase/config.js).

   The block between the precache-manifest markers is generated by
   `node tools/build-sw.mjs` -- run it before every deploy so a new
   release gets a new cache version.
========================================================= */
"use strict";

/* <precache-manifest> */
const PRECACHE_VERSION = "e952c0e853";
const PRECACHE_URLS = [
  "/",
  "/css/admin/dashboard.css",
  "/css/admin/questions.css",
  "/css/admin/quizImages.css",
  "/css/admin/quizzes.css",
  "/css/admin/subjects.css",
  "/css/auth.css",
  "/css/base.css",
  "/css/installNudge.css",
  "/css/pwa.css",
  "/css/responsive.css",
  "/css/student/dashboard.css",
  "/css/student/friendGroups.css",
  "/css/student/loadingOverlay.css",
  "/css/student/marketplace.css",
  "/css/student/myQuizzes.css",
  "/css/student/practice.css",
  "/css/student/quiz.css",
  "/css/student/result.css",
  "/css/student/reviewAnswers.css",
  "/css/verifyGate.css",
  "/css/welcomeGate.css",
  "/favicon.ico",
  "/icons/apple-touch-icon.png",
  "/icons/favicon-16.png",
  "/icons/favicon-32.png",
  "/icons/favicon-48.png",
  "/icons/icon-192.png",
  "/js/admin/cascadeDelete.js",
  "/js/admin/dangerDialog.js",
  "/js/admin/dashboard.js",
  "/js/admin/notifications.js",
  "/js/admin/questions.js",
  "/js/admin/quizzes.js",
  "/js/admin/subjects.js",
  "/js/auth.js",
  "/js/boot.js",
  "/js/cloudinary/config.js",
  "/js/emailVerificationGate.js",
  "/js/firebase/config.js",
  "/js/installPrompt.js",
  "/js/main.js",
  "/js/notificationsService.js",
  "/js/pushNotifications.js",
  "/js/pwa.js",
  "/js/sessionManager.js",
  "/js/student/analyticsWidgets.js",
  "/js/student/attemptsService.js",
  "/js/student/dashboard.js",
  "/js/student/friendGroupService.js",
  "/js/student/friendGroups.js",
  "/js/student/installNudge.js",
  "/js/student/loadingOverlay.js",
  "/js/student/marketplace.js",
  "/js/student/myQuizzes.js",
  "/js/student/navigation.js",
  "/js/student/practice.js",
  "/js/student/purchaseService.js",
  "/js/student/purchasedQuiz.js",
  "/js/student/questionNavigator.js",
  "/js/student/quiz.js",
  "/js/student/reviewAnswers.js",
  "/js/student/scrollEffects.js",
  "/js/ui/landing.js",
  "/js/ui/welcomeGate.js",
  "/manifest.json"
];
const PRECACHE_CDN = [
  "https://www.gstatic.com/firebasejs/10.12.0/firebase-analytics.js",
  "https://www.gstatic.com/firebasejs/10.12.0/firebase-app.js",
  "https://www.gstatic.com/firebasejs/10.12.0/firebase-auth.js",
  "https://www.gstatic.com/firebasejs/10.12.0/firebase-firestore.js",
  "https://www.gstatic.com/firebasejs/10.12.0/firebase-functions.js",
  "https://www.gstatic.com/firebasejs/10.12.0/firebase-messaging.js"
];
/* </precache-manifest> */

const SHELL_CACHE = `qa-shell-${PRECACHE_VERSION}`;
const CDN_CACHE = "qa-cdn-v1"; // URLs contain the SDK version, so they never go stale
const META_KEY = "/__qa_precache_meta";
const NAV_TIMEOUT_MS = 3500;
const CONCURRENCY = 4;

/* ---------------------------------------------------------
   PUSH (Firebase Cloud Messaging, background messages)
   importScripts is wrapped: if it fails (e.g. the very first
   install happens on a dead connection) caching must still work.
--------------------------------------------------------- */
try {
  importScripts(
    "https://www.gstatic.com/firebasejs/10.12.0/firebase-app-compat.js",
    "https://www.gstatic.com/firebasejs/10.12.0/firebase-messaging-compat.js",
  );

  firebase.initializeApp({
    apiKey: "AIzaSyBzKtJ5P_2bL0LWDOJt4KqMlA1Z8sMOSwo",
    authDomain: "quizarena-2c75e.firebaseapp.com",
    projectId: "quizarena-2c75e",
    storageBucket: "quizarena-2c75e.appspot.com",
    messagingSenderId: "610430960552",
    appId: "1:610430960552:web:23f5ca5be24bf2e2b4139d",
  });

  const messaging = firebase.messaging();

  messaging.onBackgroundMessage((payload) => {
    const { title, body } = payload.data || {};
    // Return the promise: the browser keeps the worker alive only
    // while it is pending (see the note in the old messaging SW).
    return self.registration.showNotification(title || "Quiz Arena", {
      body: body || "",
      icon: "/icons/icon-192.png",
      badge: "/icons/icon-192.png",
    });
  });
} catch (err) {
  console.warn("[sw] push setup skipped:", err && err.message);
}

self.addEventListener("notificationclick", (event) => {
  event.notification.close();
  event.waitUntil(
    clients
      .matchAll({ type: "window", includeUncontrolled: true })
      .then((windowClients) => {
        for (const client of windowClients) {
          if ("focus" in client) return client.focus();
        }
        if (clients.openWindow) return clients.openWindow("/");
      }),
  );
});

/* ---------------------------------------------------------
   PRECACHE
--------------------------------------------------------- */
let progress = { done: 0, total: 0, failed: 0, ready: false };
let precacheRun = null;

async function broadcast() {
  const msg = { type: "qa-precache", version: PRECACHE_VERSION, ...progress };
  const all = await self.clients.matchAll({ includeUncontrolled: true });
  all.forEach((c) => c.postMessage(msg));
}

/** A redirected response can't answer a navigation, so rebuild it clean. */
async function cleanResponse(res) {
  if (!res.redirected) return res;
  return new Response(await res.blob(), {
    status: res.status,
    statusText: res.statusText,
    headers: res.headers,
  });
}

/**
 * Runs `worker` over `queue` with limited concurrency. The queue is
 * consumed in place, so a worker may push new items onto it (the
 * Firebase crawl below relies on that).
 */
async function runPool(queue, worker) {
  const runners = Array.from({ length: CONCURRENCY }, async () => {
    while (queue.length) await worker(queue.shift());
  });
  await Promise.all(runners);
}

async function precacheShell(cache) {
  await runPool(PRECACHE_URLS.slice(), async (url) => {
    try {
      if (!(await cache.match(url))) {
        // cache:"reload" skips the HTTP cache so a new release never
        // caches yesterday's file from the browser's own cache.
        const res = await fetch(new Request(url, { cache: "reload" }));
        if (!res.ok) throw new Error(res.status);
        await cache.put(url, await cleanResponse(res));
      }
      progress.done++;
    } catch (e) {
      progress.failed++;
    }
    await broadcast();
  });
}

/** Pull `from "..."` / `import "..."` / `import("...")` specifiers out of a module. */
function findImports(source) {
  const found = new Set();
  const re = /(?:\bfrom\s*|\bimport\s*\(?\s*)["']([^"']+)["']/g;
  let m;
  while ((m = re.exec(source))) found.add(m[1]);
  return [...found];
}

async function precacheFirebaseSdk() {
  const cdn = await caches.open(CDN_CACHE);
  const queue = PRECACHE_CDN.slice();
  const seen = new Set(queue);
  progress.total += queue.length;

  // The SDK files import each other, so walk the import graph.
  await runPool(queue, async (url) => {
    try {
      let res = await cdn.match(url);
      if (!res) {
        const fetched = await fetch(url, { mode: "cors", credentials: "omit" });
        if (!fetched.ok) throw new Error(fetched.status);
        await cdn.put(url, fetched.clone());
        res = fetched;
      }
      const text = await res.clone().text();
      for (const spec of findImports(text)) {
        let next;
        try {
          next = new URL(spec, url);
        } catch {
          continue;
        }
        if (next.hostname !== "www.gstatic.com" || !next.pathname.startsWith("/firebasejs/")) continue;
        if (seen.has(next.href)) continue;
        seen.add(next.href);
        progress.total++;
        queue.push(next.href);
      }
      progress.done++;
    } catch (e) {
      progress.failed++;
    }
    await broadcast();
  });
}

function precacheAll() {
  if (precacheRun) return precacheRun;
  precacheRun = (async () => {
    progress = { done: 0, total: PRECACHE_URLS.length, failed: 0, ready: false };
    await broadcast();

    const shell = await caches.open(SHELL_CACHE);
    await precacheShell(shell);
    await precacheFirebaseSdk();

    progress.ready = progress.failed === 0;
    await shell.put(
      META_KEY,
      new Response(JSON.stringify({ version: PRECACHE_VERSION, ...progress, at: Date.now() }), {
        headers: { "Content-Type": "application/json" },
      }),
    );
    await broadcast();
  })().finally(() => {
    precacheRun = null;
  });
  return precacheRun;
}

self.addEventListener("install", (event) => {
  self.skipWaiting();
  // Never reject: an install that fails on a weak network would leave the
  // site with no service worker at all (and no install prompt). Missing
  // files are topped up on activate / next start instead.
  event.waitUntil(precacheAll().catch((e) => console.warn("[sw] precache:", e)));
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    (async () => {
      const names = await caches.keys();
      await Promise.all(
        names
          .filter((n) => n.startsWith("qa-shell-") && n !== SHELL_CACHE)
          .map((n) => caches.delete(n)),
      );
      await self.clients.claim();
      // Top up anything the install couldn't fetch (fast no-op when complete).
      precacheAll().catch(() => {});
    })(),
  );
});

self.addEventListener("message", (event) => {
  const data = event.data || {};
  if (data.type === "SKIP_WAITING") self.skipWaiting();
  if (data.type === "PRECACHE_RETRY") event.waitUntil(precacheAll().catch(() => {}));
});

/* ---------------------------------------------------------
   FETCH
--------------------------------------------------------- */
const OFFLINE_HTML = `<!doctype html><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Quiz Arena is offline</title>
<body style="margin:0;min-height:100dvh;display:grid;place-items:center;background:#2e1065;color:#f5f3ff;font:16px/1.5 system-ui,sans-serif;text-align:center;padding:24px">
<div><h1 style="font-size:1.6rem;margin:0 0 8px">You're offline</h1>
<p style="margin:0 0 20px;opacity:.8">Connect to the internet once and Quiz Arena will be saved on your phone.</p>
<button onclick="location.reload()" style="font:inherit;font-weight:700;padding:14px 22px;border:0;border-radius:14px;background:#ffb454;color:#2a1200">Try again</button></div>`;

function offlinePage() {
  return new Response(OFFLINE_HTML, {
    status: 503,
    headers: { "Content-Type": "text/html; charset=utf-8" },
  });
}

async function handleNavigation(event) {
  const cache = await caches.open(SHELL_CACHE);
  const cached = await cache.match("/");

  const network = fetch(event.request).then(async (res) => {
    // Keep the cached shell fresh for next time.
    if (res && res.ok && new URL(event.request.url).pathname === "/") {
      await cache.put("/", await cleanResponse(res.clone()));
    }
    return res;
  });
  // Let the cache refresh finish even when we answered from cache.
  event.waitUntil(network.catch(() => {}));

  if (!cached) return network.catch(() => offlinePage());

  const timeout = new Promise((resolve) => setTimeout(() => resolve(cached), NAV_TIMEOUT_MS));
  return Promise.race([network, timeout]).catch(() => cached);
}

async function staleWhileRevalidate(event) {
  const cache = await caches.open(SHELL_CACHE);
  const cached = await cache.match(event.request);

  const network = fetch(event.request)
    .then((res) => {
      if (res && res.ok && res.type === "basic") cache.put(event.request, res.clone());
      return res;
    })
    .catch(() => null);

  if (cached) {
    event.waitUntil(network);
    return cached;
  }
  return (await network) || Response.error();
}

async function cacheFirst(request, cacheName) {
  const cache = await caches.open(cacheName);
  const hit = await cache.match(request);
  if (hit) return hit;
  const res = await fetch(request);
  if (res && res.ok) cache.put(request, res.clone());
  return res;
}

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;

  const url = new URL(req.url);

  if (url.origin === self.location.origin) {
    if (url.pathname.startsWith("/__/")) return; // Firebase reserved paths
    if (req.headers.has("range")) return;
    if (req.mode === "navigate") {
      event.respondWith(handleNavigation(event));
    } else {
      event.respondWith(staleWhileRevalidate(event));
    }
    return;
  }

  if (url.hostname === "www.gstatic.com" && url.pathname.startsWith("/firebasejs/")) {
    event.respondWith(cacheFirst(req, CDN_CACHE));
  }
  // anything else: not intercepted
});
